### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pretrained_model_name_or_path'

### ISSUE THREAD

**Issue by ShadowStorm0** [Thund3rPat/kohya_ss-linux#13]
I don't understand why I get `TypeError: __init__() got an unexpected keyword argument 'pretrained_model_name_or_path'` after I click on train. The source model I chose was "AbyssOrangeMix2_hard.safetensors"

**Comment by Thund3rPat** [comment]
Please enter the absolute path to the model:
for example `/home/your_name/models/AbyssOrangeMix2_hard.safetensors`

**Comment by ShadowStorm0** [comment]
![Screenshot from 2023-02-26 15-51-12](https://user-images.githubusercontent.com/41564329/221439569-43196c6b-2d27-463e-aa08-559596d9a433.png) This is what I put `/media/username/Secondary Drive/stable-diffusion-webui/models/Stable-diffusion/AbyssOrangeMix2_hard.safetensors` Still giving the same error

**Comment by ShadowStorm0** [comment]
The path is what I get with I use the `pwd` command

**Comment by Thund3rPat** [comment]
The path looks fine to me. You should definitely untick v2.

**Comment by ShadowStorm0** [comment]
I unticked v2 and I'm still getting the same error

**Comment by Thund3rPat** [comment]
Could you paste the whole error message?

**Comment by ShadowStorm0** [comment]
`Traceback (most recent call last):
  File "/media/username/Secondary Drive/kohya_ss-linux/venv/bin/accelerate", line 10, in <module>
    sys.exit(main())
  File "/media/username/Secondary Drive/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/media/username/Secondary Drive/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1000, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/media/username/Secondary Drive/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/media/username/Secondary Drive/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/config/config_args.py", line 122, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'pretrained_model_name_or_path'`

**Comment by Thund3rPat** [comment]
Ok, I think I found out the problem. Please run `accelerate config` again and leave the path to the configuration file empty for now, then try again.

**Comment by Thund3rPat** [comment]
You accidentally overwrote the accelerate config file. The path you are supposed to specify, at the top right, is a config file specific to kohya gui to save which training parameters you used. You should create a new file for that.
I hope this helped you.

**Comment by ShadowStorm0** [comment]
Thank you.
You suggestion solved my issue

**Comment by Thund3rPat** [comment]
You are welcome :)
